/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as VacanciesImport } from './routes/vacancies'
import { Route as TalentPoolImport } from './routes/talent-pool'
import { Route as EditCompanyProfileImport } from './routes/edit-company-profile'
import { Route as CreateVacancyImport } from './routes/create-vacancy'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const VacanciesRoute = VacanciesImport.update({
  path: '/vacancies',
  getParentRoute: () => rootRoute,
} as any)

const TalentPoolRoute = TalentPoolImport.update({
  path: '/talent-pool',
  getParentRoute: () => rootRoute,
} as any)

const EditCompanyProfileRoute = EditCompanyProfileImport.update({
  path: '/edit-company-profile',
  getParentRoute: () => rootRoute,
} as any)

const CreateVacancyRoute = CreateVacancyImport.update({
  path: '/create-vacancy',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/create-vacancy': {
      id: '/create-vacancy'
      path: '/create-vacancy'
      fullPath: '/create-vacancy'
      preLoaderRoute: typeof CreateVacancyImport
      parentRoute: typeof rootRoute
    }
    '/edit-company-profile': {
      id: '/edit-company-profile'
      path: '/edit-company-profile'
      fullPath: '/edit-company-profile'
      preLoaderRoute: typeof EditCompanyProfileImport
      parentRoute: typeof rootRoute
    }
    '/talent-pool': {
      id: '/talent-pool'
      path: '/talent-pool'
      fullPath: '/talent-pool'
      preLoaderRoute: typeof TalentPoolImport
      parentRoute: typeof rootRoute
    }
    '/vacancies': {
      id: '/vacancies'
      path: '/vacancies'
      fullPath: '/vacancies'
      preLoaderRoute: typeof VacanciesImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/create-vacancy': typeof CreateVacancyRoute
  '/edit-company-profile': typeof EditCompanyProfileRoute
  '/talent-pool': typeof TalentPoolRoute
  '/vacancies': typeof VacanciesRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/create-vacancy': typeof CreateVacancyRoute
  '/edit-company-profile': typeof EditCompanyProfileRoute
  '/talent-pool': typeof TalentPoolRoute
  '/vacancies': typeof VacanciesRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/create-vacancy': typeof CreateVacancyRoute
  '/edit-company-profile': typeof EditCompanyProfileRoute
  '/talent-pool': typeof TalentPoolRoute
  '/vacancies': typeof VacanciesRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/create-vacancy'
    | '/edit-company-profile'
    | '/talent-pool'
    | '/vacancies'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/create-vacancy'
    | '/edit-company-profile'
    | '/talent-pool'
    | '/vacancies'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/create-vacancy'
    | '/edit-company-profile'
    | '/talent-pool'
    | '/vacancies'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CreateVacancyRoute: typeof CreateVacancyRoute
  EditCompanyProfileRoute: typeof EditCompanyProfileRoute
  TalentPoolRoute: typeof TalentPoolRoute
  VacanciesRoute: typeof VacanciesRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CreateVacancyRoute: CreateVacancyRoute,
  EditCompanyProfileRoute: EditCompanyProfileRoute,
  TalentPoolRoute: TalentPoolRoute,
  VacanciesRoute: VacanciesRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/create-vacancy",
        "/edit-company-profile",
        "/talent-pool",
        "/vacancies"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/create-vacancy": {
      "filePath": "create-vacancy.tsx"
    },
    "/edit-company-profile": {
      "filePath": "edit-company-profile.tsx"
    },
    "/talent-pool": {
      "filePath": "talent-pool.tsx"
    },
    "/vacancies": {
      "filePath": "vacancies.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
